apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\sktmf\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: coupon-api
  name: coupon-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: coupon-api
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\sktmf\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/project-default: "true"
        io.kompose.service: coupon-api
    spec:
      containers:
        - env:
            - name: SPRING_PROFILES_ACTIVE
              value: production
            - name: spring.data.redis.host
              value: coupon-redis
            - name: spring.data.redis.port
              value: "6380"
          image: cloudbreak6th/coupon-api:multi_v0.1
          name: coupon-api
          ports:
            - containerPort: 8080
              hostPort: 8080
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
