apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\sktmf\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert
    kompose.version: 1.31.2 (a92241f79)
    mode: standalone
    name: redis
  creationTimestamp: null
  labels:
    io.kompose.service: redis
  name: redis
spec:
  ports:
    - name: "6380"
      port: 6380
      targetPort: 6380
  selector:
    io.kompose.service: redis
status:
  loadBalancer: {}
