apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\sktmf\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert
    kompose.version: 1.31.2 (a92241f79)
    mode: standalone
    name: redis
  creationTimestamp: null
  labels:
    io.kompose.service: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redis
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\sktmf\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert
        kompose.version: 1.31.2 (a92241f79)
        mode: standalone
        name: redis
      creationTimestamp: null
      labels:
        io.kompose.network/project-default: "true"
        io.kompose.service: redis
    spec:
      containers:
        - args:
            - redis-server
            - --port
            - "6380"
          image: redis:7.2-alpine
          name: coupon-redis
          ports:
            - containerPort: 6380
              hostPort: 6380
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
